#! /bin/sh

bspc config border_width        0
bspc config window_gap         20

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor DVI-D-0 -d I II III IV V
bspc monitor HDMI-0 -d VI VII VIII IX X

bspc rule -a Google-chrome-beta desktop=^1 floating=on private=on
bspc rule -a Steam floating=on desktop=^5 
bspc rule -a urxvt floating=on

